title: Zachary Hamida # your name (or website title) here
logo: "/images/logo.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  <h2>Zachary Hamida</h2>
  Ph.D. | B. E. Civil Engineering
  <br>
  M.Sc. Computational Science
  <br><br>
  <b>Research Interests</b> <br>
  <b>Theory:</b> control theory, machine learning, optimization <br>
  <b>Applications:</b> structural health monitoring; maintenance planning; oil field planning.
  <br><br>
  <b> Activities </b>
  <br>
  <b>[2021-]</b> <a href="http://profs.polymtl.ca/jagoulet/Site/Goulet_web_page_ZHAMIDA.html"> Postdoctoral Researcher </a> <br>
  <b>[2013-]</b> <a href="https://www.behance.net/zachamida"> Graphic Design </a>
  <br><br>
  <b>Contact:</b>
  <br>
  <a href = "mailto: zac.hamida@gmail.com">Email</a> | 
  <a href="https://scholar.google.ca/citations?user=J7NHpmYAAAAJ&hl=en&oi=ao">Scholar</a> |   
  <a href="https://www.linkedin.com/in/zacharyhamida/">LinkedIn</a> |   
  <a href="https://github.com/zachamida">Github</a>
  <a href="/pdf/ZacharyHamidaCV.pdf">Resumé</a> 
theme: jekyll-theme-minimal
google_analytics: UA-216599147-1 # your Google Analytics tracking ID here
