title: Zachary Hamida # your name (or website title) here
logo: "/images/logo.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  <h2>Zachary Hamida</h2>
  Ph.D. | B. E. Civil Engineering
  <br>
  M.Sc. Computational Science
  <br><br>
  My research interests centre around the development and utilization of machine learning methods in solving engineering problems. In addition to research, I have worked with few startups as a data scientist.
  <br><br>
  <b> Activities </b>
  <br>
  <b>[2021-]</b> <a href="http://profs.polymtl.ca/jagoulet/Site/Goulet_web_page_ZHAMIDA.html"> Postdoctoral Research Associate </a> <br>
  <b>[2013-]</b> <a href="https://www.behance.net/zachamida"> Graphic Design </a>
  <br><br>
  <b>Contact:</b>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
